function summary = runImpactAngleCases()
%RUNIMPACTANGLECASES Run and save five terminal impact-angle cases.

modelName = "Ctrl_For_HRV_20260625";
outputFolder = fullfile(pwd, "impact_angle_results");
if ~isfolder(outputFolder)
    mkdir(outputFolder);
end
delete(fullfile(outputFolder, "case_*_parameters.mat"));
delete(fullfile(outputFolder, "case_*_flight_data.mat"));

thetaDesiredDeg = [-41, -43, -45, -47.5, -50];
psiDesiredDeg = [14.5, 16, 17.5, 19, 20.5];
thetaInitialDeg = [-41, -43, -45, -47.5, -50];
psiInitialDeg = [14.5, 16, 17.5, 19, 20.5];
initialAltitudeM = [25000, 25000, 25000, 25000, 25000];
targetPositionM = [25000, 7500, 0];
horizontalRangeM = initialAltitudeM ./ tand(abs(thetaInitialDeg));
initialPositionXM = targetPositionM(1) - ...
    horizontalRangeM.*cosd(psiInitialDeg);
initialPositionYM = targetPositionM(2) - ...
    horizontalRangeM.*sind(psiInitialDeg);
caseCount = numel(thetaDesiredDeg);
summary = repmat(emptySummary(), caseCount, 1);

for caseIndex = 1:caseCount
    bdclose(modelName);
    clear functions;
    load_system(modelName);
    set_param(modelName + "/Constant3", "Value", ...
        num2str(thetaDesiredDeg(caseIndex), "%.6g"));
    set_param(modelName + "/Constant4", "Value", ...
        num2str(psiDesiredDeg(caseIndex), "%.6g"));
    initialState = struct( ...
        "H0", initialAltitudeM(caseIndex), "V0", 2800, ...
        "X0", initialPositionXM(caseIndex), ...
        "Y0", initialPositionYM(caseIndex), ...
        "theta0", thetaInitialDeg(caseIndex)*pi/180, ...
        "psi0", psiInitialDeg(caseIndex)*pi/180);
    assignin("base", "HRV_INIT", initialState);

    simulationOutput = sim(modelName, ...
        StopTime="32", ReturnWorkspaceOutputs="on");
    [result, flightData] = evaluateSimulation(simulationOutput, ...
        thetaDesiredDeg(caseIndex), psiDesiredDeg(caseIndex), ...
        thetaInitialDeg(caseIndex), psiInitialDeg(caseIndex), ...
        initialPositionXM(caseIndex), initialPositionYM(caseIndex), ...
        initialAltitudeM(caseIndex));
    parameters = makeParameterRecord(result);

    caseTag = sprintf("case_%02d_theta_%+05.1f_psi_%+04.1f", ...
        caseIndex, thetaDesiredDeg(caseIndex), psiDesiredDeg(caseIndex));
    save(fullfile(outputFolder, caseTag + "_parameters.mat"), "parameters");
    save(fullfile(outputFolder, caseTag + "_flight_data.mat"), "flightData");
    summary(caseIndex) = result;

    fprintf("Case %d: miss %.3f m, theta %.3f deg, psi %.3f deg\n", ...
        caseIndex, result.missDistanceM, result.terminalThetaDeg, ...
        result.terminalPsiDeg);
end

set_param(modelName + "/Constant3", "Value", "-45");
set_param(modelName + "/Constant4", "Value", "17.5");
save_system(modelName);
evalin("base", "clear HRV_INIT");
save(fullfile(outputFolder, "impact_angle_summary.mat"), "summary");
plotImpactAngleComparison(summary, outputFolder);
assignin("base", "IMPACT_ANGLE_SUMMARY", summary);
end

function [result, flightData] = evaluateSimulation(simOut, thetaDesired, ...
    psiDesired, thetaInitial, psiInitial, initialX, initialY, initialAltitude)
time = simOut.Scope_X(:, 1);
position = [simOut.Scope_X(:, 2), simOut.Scope_Y(:, 2), ...
    simOut.Scope_H(:, 2)];
target = simOut.Scope_position_target1(1, 2:4);
[missDistance, closestTime] = segmentMissDistance(time, position, target);

thetaDeg = simOut.Scope_theta(:, 2);
psiDeg = simOut.Scope_psi(:, 2);
normalLoadSignal = simOut.logsout.get("ny_cmd_log").Values;
lateralLoadSignal = simOut.logsout.get("nz_cmd_log").Values;
terminalTheta = interp1(time, thetaDeg, closestTime, "linear", "extrap");
terminalPsi = interp1(time, psiDeg, closestTime, "linear", "extrap");

result = emptySummary();
result.thetaDesiredDeg = thetaDesired;
result.psiDesiredDeg = psiDesired;
result.thetaInitialDeg = thetaInitial;
result.psiInitialDeg = psiInitial;
result.initialPositionXM = initialX;
result.initialPositionYM = initialY;
result.initialAltitudeM = initialAltitude;
result.missDistanceM = missDistance;
result.closestTimeS = closestTime;
result.terminalThetaDeg = terminalTheta;
result.terminalPsiDeg = terminalPsi;
result.thetaErrorDeg = terminalTheta - thetaDesired;
result.psiErrorDeg = wrapTo180(terminalPsi - psiDesired);
result.hit = missDistance <= 10;

flightData = struct( ...
    "description", "Complete HRV terminal-flight time history", ...
    "timeS", time, ...
    "positionXM", simOut.Scope_X(:, 2), ...
    "positionYM", simOut.Scope_Y(:, 2), ...
    "altitudeM", simOut.Scope_H(:, 2), ...
    "speedMps", simOut.Scope_V(:, 2), ...
    "mach", simOut.Scope_Ma(:, 2), ...
    "flightPathThetaDeg", thetaDeg, ...
    "flightPathPsiDeg", psiDeg, ...
    "angleOfAttackDeg", simOut.Scope_alpha(:, 2), ...
    "sideslipDeg", simOut.Scope_beta(:, 2), ...
    "bankAngleDeg", simOut.Scope_miu(:, 2), ...
    "normalLoadTimeS", normalLoadSignal.Time, ...
    "normalLoadCommandG", normalLoadSignal.Data, ...
    "lateralLoadTimeS", lateralLoadSignal.Time, ...
    "lateralLoadCommandG", lateralLoadSignal.Data, ...
    "aileronDeg", simOut.Scope_delta_a(:, 2), ...
    "elevatorDeg", simOut.Scope_delta_e(:, 2), ...
    "rudderDeg", simOut.Scope_delta_r(:, 2), ...
    "desiredThetaDeg", thetaDesired, ...
    "desiredPsiDeg", psiDesired, ...
    "initialThetaDeg", thetaInitial, ...
    "initialPsiDeg", psiInitial, ...
    "initialPositionXM", initialX, ...
    "initialPositionYM", initialY, ...
    "initialAltitudeM", initialAltitude, ...
    "targetPositionM", target, ...
    "result", result);
end

function parameters = makeParameterRecord(result)
parameters = struct;
parameters.description = ...
    "Impact-angle guidance parameters and their physical meanings";
parameters.desiredFlightPathInclinationDeg = result.thetaDesiredDeg;
parameters.desiredFlightPathInclinationMeaning = ...
    "Terminal flight-path inclination relative to local horizontal [deg]";
parameters.desiredFlightPathAzimuthDeg = result.psiDesiredDeg;
parameters.desiredFlightPathAzimuthMeaning = ...
    "Terminal flight-path azimuth measured from +X toward +Y [deg]";
parameters.initialFlightPathInclinationDeg = result.thetaInitialDeg;
parameters.initialFlightPathInclinationMeaning = ...
    "Initial flight-path inclination relative to local horizontal [deg]";
parameters.initialFlightPathAzimuthDeg = result.psiInitialDeg;
parameters.initialFlightPathAzimuthMeaning = ...
    "Initial flight-path azimuth measured from +X toward +Y [deg]";
parameters.initialPositionXM = result.initialPositionXM;
parameters.initialPositionYM = result.initialPositionYM;
parameters.initialPositionMeaning = ...
    "Initial inertial horizontal position selected on the desired impact line [m]";
parameters.navigationConstantTheta = 4.0;
parameters.navigationConstantThetaMeaning = ...
    "Vertical-plane proportional-navigation constant [-]";
parameters.navigationConstantPsi = 4.0;
parameters.navigationConstantPsiMeaning = ...
    "Horizontal-plane proportional-navigation constant [-]";
parameters.angleFeedbackGainTheta = 0.8;
parameters.angleFeedbackGainThetaMeaning = ...
    "Vertical LOS-to-flight-path feedback gain [-]";
parameters.angleFeedbackGainPsi = 0.8;
parameters.angleFeedbackGainPsiMeaning = ...
    "Horizontal LOS-to-flight-path feedback gain [-]";
parameters.terminalAimpointFraction = 0.02;
parameters.terminalAimpointFractionMeaning = ...
    "Virtual aimpoint setback as a fraction of true range [-]";
parameters.maximumAimpointSetbackM = 1000;
parameters.maximumAimpointSetbackMeaning = ...
    "Maximum virtual aimpoint setback from target [m]";
parameters.lateralAimBiasM = 22;
parameters.lateralAimBiasMeaning = ...
    "Fixed lateral aim compensation for closed-loop lag [m]";
parameters.normalLoadLimitsG = [-8, 8];
parameters.normalLoadLimitsMeaning = ...
    "Lower and upper vertical-plane load-command limits [g]";
parameters.lateralLoadLimitsG = [-4, 4];
parameters.lateralLoadLimitsMeaning = ...
    "Lower and upper lateral load-command limits [g]";
parameters.hitRadiusM = 10;
parameters.hitRadiusMeaning = "Continuous-trajectory hit radius [m]";
parameters.initialAltitudeM = result.initialAltitudeM;
parameters.initialSpeedMps = 2800;
parameters.targetPositionM = [25000, 7500, 0];
end

function [minimumDistance, closestTime] = segmentMissDistance(time, position, target)
minimumDistance = inf;
closestTime = time(1);
for sampleIndex = 1:size(position, 1)-1
    segment = position(sampleIndex+1, :) - position(sampleIndex, :);
    denominator = dot(segment, segment);
    if denominator > 0
        fraction = dot(target-position(sampleIndex, :), segment)/denominator;
        fraction = min(max(fraction, 0), 1);
    else
        fraction = 0;
    end
    candidate = position(sampleIndex, :) + fraction*segment;
    candidateDistance = norm(candidate-target);
    if candidateDistance < minimumDistance
        minimumDistance = candidateDistance;
        closestTime = time(sampleIndex) + ...
            fraction*(time(sampleIndex+1)-time(sampleIndex));
    end
end
end

function angleDeg = wrapTo180(angleDeg)
angleDeg = mod(angleDeg + 180, 360) - 180;
end

function result = emptySummary()
result = struct( ...
    "thetaDesiredDeg", NaN, "psiDesiredDeg", NaN, ...
    "thetaInitialDeg", NaN, "psiInitialDeg", NaN, ...
    "initialPositionXM", NaN, "initialPositionYM", NaN, ...
    "initialAltitudeM", NaN, ...
    "missDistanceM", NaN, "closestTimeS", NaN, ...
    "terminalThetaDeg", NaN, "terminalPsiDeg", NaN, ...
    "thetaErrorDeg", NaN, "psiErrorDeg", NaN, "hit", false);
end
