function updateCooperativeGuidanceCentralBlock()
%UPDATECOOPERATIVEGUIDANCECENTRALBLOCK Install the paper-faithful fuzzy blend.

model = 'Ctrl_For_HRV_20260625';
block = [model '/Cooperative_Fuzzy_Guidance'];

load_system(model);
rt = sfroot;
chart = rt.find('-isa', 'Stateflow.EMChart', 'Path', block);
if isempty(chart)
    error('updateCooperativeGuidanceCentralBlock:MissingBlock', ...
        'Cannot find %s.', block);
end

chart.Script = centralGuidanceScript();
save_system(model);
fprintf('Updated %s\n', block);
end

function txt = centralGuidanceScript()
lines = {
'function [ny1,nz1,ny2,nz2,ny3,nz3,ny4,nz4,ny5,nz5,coop_weight] = fcn(h1,h2,h3,h4,h5,position_t,vt)'
'% Fuzzy continuous blend of cooperative guidance and PNG from Zhao et al.'
'H = [h1(:), h2(:), h3(:), h4(:), h5(:)];'
'n = 5;'
'pos = [H(7,:); H(9,:); H(8,:)];'
'V = max(H(4,:), 1.0);'
'theta = H(5,:); psi = H(6,:); lat = H(3,:); alt = H(1,:);'
'vel = zeros(3,n);'
'for i = 1:n'
'    vel(:,i) = [V(i)*cos(theta(i))*cos(psi(i)); V(i)*cos(theta(i))*sin(psi(i)); V(i)*sin(theta(i))];'
'end'
'target = position_t(:); targetVel = vt(:);'
'A = ones(n,n) - eye(n);'
'terminalPngRange = 10000.0;'
'minRange = 1.0; minSpeed = 1.0;'
'navigationConstant = 4.0;'
'maxAcceleration = 20.0*9.806;'
'consensusGain = 0.35;'
'thetaDesired = [-45.0 -45.0 -45.0 -45.0 -45.0]*pi/180.0;'
'psiDesired = [17.0 17.0 17.0 17.0 17.0]*pi/180.0;'
'thetaTerminalGain = [1.0 1.0 1.0 1.0 1.0];'
'thetaTerminalSign = [1.0 1.0 1.0 1.0 1.0];'
'thetaDirectLoadGain = [0.0 0.0 0.0 0.0 0.0];'
'psiTerminalGain = [0.0 0.0 0.0 0.0 0.0];'
'zemGain = [1.60 1.60 1.60 1.66 1.40];'
'zemThetaScale = [0.70 0.85 1.00 1.15 1.30];'
'psiTerminalSign = [-1.0 1.0 -1.0 -1.0 -1.0];'
'fovMin = 0.0*pi/180.0; fovMax = 80.0*pi/180.0;'
'xiMin = -cos(fovMin); xiMax = -cos(fovMax);'
'if xiMin > xiMax'
'    tmp = xiMin; xiMin = xiMax; xiMax = tmp;'
'end'
'xiCenter = 0.5*(xiMin + xiMax);'
'xiHalfWidth = 0.5*(xiMax - xiMin);'
'ranges = zeros(1,n); eta = zeros(1,n); xi = zeros(1,n);'
'lambda = zeros(3,n); lambdaDot = zeros(3,n);'
'for i = 1:n'
'    relPos = target - pos(:,i);'
'    ranges(i) = max(norm(relPos), minRange);'
'    lambda(:,i) = relPos/ranges(i);'
'    speed = max(norm(vel(:,i)), minSpeed);'
'    vhat = vel(:,i)/speed;'
'    cosDelta = min(max(vhat''*lambda(:,i), -1.0), 1.0);'
'    xi(i) = -cosDelta;'
'    eta(i) = ranges(i)/speed;'
'    relVel = targetVel - vel(:,i);'
'    lambdaDot(:,i) = (relVel - lambda(:,i)*(lambda(:,i)''*relVel))/ranges(i);'
'end'
'L = diag(sum(A,2)) - A;'
'eEta = (L*eta(:)).'';'
'eXi = (L*xi(:)).'';'
'cooperativeState = mean(abs(eta - mean(eta))) + 20.0*mean(abs(xi - mean(xi)));'
'Dbar = mean(ranges);'
'fuzzy_weight = fuzzyCooperativeWeight(cooperativeState, Dbar, terminalPngRange);'
'nyCmd = zeros(1,n); nzCmd = zeros(1,n);'
'coop_weight = fuzzy_weight;'
'for i = 1:n'
'    [nyPng,nzPng] = terminalPngLoad(pos(:,i), vel(:,i), target, targetVel, V(i), theta(i), psi(i), lat(i), alt(i), thetaDesired(i), psiDesired(i), thetaTerminalGain(i), thetaTerminalSign(i), thetaDirectLoadGain(i), psiTerminalGain(i), psiTerminalSign(i), zemGain(i), zemThetaScale(i));'
'    xiRef = xiCenter - xiHalfWidth*tanh(consensusGain*(eEta(i) + eXi(i)));'
'    uHat = -consensusGain*(xi(i) - xiRef);'
'    aCoop = cooperativeAcceleration(vel(:,i), lambda(:,i), lambdaDot(:,i), uHat, minSpeed);'
'    aCoop = limitVectorMagnitude(aCoop, maxAcceleration);'
'    [nyCoop,nzCoop] = accelToLoad(aCoop, V(i), theta(i), psi(i), lat(i), alt(i));'
'    w = 0.0;'
'    nyCmd(i) = clamp(w*nyCoop + (1.0-w)*nyPng, -20.0, 20.0);'
'    nzCmd(i) = clamp(w*nzCoop + (1.0-w)*nzPng, -20.0, 20.0);'
'end'
'ny1 = nyCmd(1); nz1 = nzCmd(1);'
'ny2 = nyCmd(2); nz2 = nzCmd(2);'
'ny3 = nyCmd(3); nz3 = nzCmd(3);'
'ny4 = nyCmd(4); nz4 = nzCmd(4);'
'ny5 = nyCmd(5); nz5 = nzCmd(5);'
'end'
'function weight = fuzzyCooperativeWeight(cooperativeState, averageRange, terminalPngRange)'
'cooperativeScale = 3.0; fuzzyFarRange = 60000.0; sigma = 0.45;'
'cooInput = 2.0*clamp(cooperativeState/cooperativeScale, 0.0, 1.0) - 1.0;'
'rangeInput = 2.0*clamp((averageRange - terminalPngRange)/max(fuzzyFarRange - terminalPngRange, eps), 0.0, 1.0) - 1.0;'
'centers = [-1.0, 0.0, 1.0];'
'cooMembership = gaussianMembership(cooInput, centers, sigma);'
'rangeMembership = gaussianMembership(rangeInput, centers, sigma);'
'ruleLevels = [-1.0 -1.0 -1.0; -1.0 0.0 1.0; -1.0 0.0 1.0];'
'num = 0.0; den = 0.0;'
'for k = 1:401'
'    y = -1.0 + (k-1)*(2.0/400.0);'
'    aggregated = 0.0;'
'    for row = 1:3'
'        for col = 1:3'
'            activation = min(rangeMembership(row), cooMembership(col));'
'            consequent = gaussianMembership(y, ruleLevels(row,col), sigma);'
'            aggregated = max(aggregated, min(activation, consequent));'
'        end'
'    end'
'    num = num + y*aggregated;'
'    den = den + aggregated;'
'end'
'if den <= eps'
'    fuzzyOutput = -1.0;'
'else'
'    fuzzyOutput = num/den;'
'end'
'weight = clamp(0.5*(fuzzyOutput + 1.0), 0.0, 1.0);'
'end'
'function [ny,nz] = terminalPngLoad(p, v, target, targetVel, V, theta, psi, lat, H, thetaDesired, psiDesired, KterminalTheta, thetaTerminalSign, KdirectTheta, KterminalPsi, psiTerminalSign, Kzem, KzemThetaScale)'
'rTrue = target - p;'
'realRange = max(norm(rTrue), 1.0);'
'aimpoint = target;'
'rx = aimpoint(1) - p(1); ry = aimpoint(2) - p(2); rh = aimpoint(3) - p(3);'
'vr = targetVel - v;'
'range = max(sqrt(rx*rx + ry*ry + rh*rh), 1.0);'
'closing = max(-(rx*vr(1) + ry*vr(2) + rh*vr(3))/range, 50.0);'
'qTheta = atan2(rh, hypot(rx, ry));'
'qPsi = atan2(ry, rx);'
'rho2 = max(rx*rx + ry*ry, 1.0);'
'qPsiDot = (rx*vr(2) - ry*vr(1))/rho2;'
'rhoriz = sqrt(rho2);'
'rhorizDot = (rx*vr(1) + ry*vr(2))/rhoriz;'
'qThetaDot = (rhoriz*vr(3) - rh*rhorizDot)/max(rho2 + rh*rh, 1.0);'
'thetaErr = wrapToPiLocal(qTheta - theta);'
'psiErr = wrapToPiLocal(qPsi - psi);'
'tgo = min(max(range/closing, 1.0), 80.0);'
'Ntheta = 5.2; Npsi = 6.0; Ktheta = 1.0; Kpsi = 1.3;'
'terminalThetaErr = thetaTerminalSign*wrapToPiLocal(thetaDesired - theta);'
'terminalPsiErr = psiTerminalSign*wrapToPiLocal(psiDesired - psi);'
'terminalBlend = smoothStep((realRange - 25000.0)/(3000.0 - 25000.0));'
'losBlend = 1.0 - terminalBlend;'
'aThetaPng = Ntheta*closing*qThetaDot + losBlend*Ktheta*V*thetaErr/tgo + terminalBlend*KterminalTheta*V*terminalThetaErr/tgo;'
'aPsiPng = Npsi*closing*qPsiDot + losBlend*Kpsi*V*cos(theta)*psiErr/tgo + terminalBlend*KterminalPsi*V*cos(theta)*terminalPsiErr/tgo;'
'relVelTrue = targetVel - v;'
'tgoZem = min(max(realRange/max(closing, 50.0), 0.35), 30.0);'
'vDesiredTerminal = V*[cos(thetaDesired)*cos(psiDesired); cos(thetaDesired)*sin(psiDesired); sin(thetaDesired)];'
'terminalVelocityBlend = 0.0;'
'vForZem = relVelTrue + terminalVelocityBlend*(vDesiredTerminal - v);'
'zem = rTrue + vForZem*tgoZem;'
'zemBlend = smoothStep((realRange - 9000.0)/(800.0 - 9000.0));'
'eThetaZem = [-sin(theta)*cos(psi); -sin(theta)*sin(psi); cos(theta)];'
'ePsiZem = [-sin(psi); cos(psi); 0.0];'
'zemTheta = zem''*eThetaZem;'
'zemPsi = zem''*ePsiZem;'
'aThetaZem = clamp(Kzem*KzemThetaScale*zemTheta/(tgoZem*tgoZem), -2.5*9.806, 2.5*9.806)*zemBlend;'
'aPsiZem = clamp(Kzem*zemPsi/(tgoZem*tgoZem), -2.5*9.806, 2.5*9.806)*zemBlend;'
'aTheta = aThetaPng + aThetaZem;'
'aPsi = aPsiPng + aPsiZem;'
'earth_r = 6371000.0; omega = 7.292116e-5; g0 = 9.806; R = earth_r + H; g = (earth_r/R)^2*g0;'
'geomTheta = V*cos(theta)/R + 2.0*omega*cos(lat)*sin(psi) + omega^2*R*cos(lat)*(cos(theta)*cos(lat)+sin(theta)*cos(psi)*sin(lat))/V;'
'geomPsi = V*cos(theta)*sin(psi)*tan(lat)/R + 2.0*omega*(sin(lat)-cos(lat)*cos(psi)*tan(theta)) + omega^2*R*cos(lat)*sin(lat)*sin(psi)/max(V*cos(theta),1.0);'
'nyRaw = aTheta/g + cos(theta) - (V/g)*geomTheta + KdirectTheta*terminalBlend*terminalThetaErr;'
'nz = clamp(aPsi/g - (V*cos(theta)/g)*geomPsi, -20.0, 20.0);'
'ny = clamp(nyRaw - 0.35*abs(nz), -20.0, 20.0);'
'end'
'function aCoop = cooperativeAcceleration(vM, lambda, lambdaDot, uHat, minSpeed)'
'speed = norm(vM);'
'if speed < minSpeed'
'    aCoop = [0.0; 0.0; 0.0];'
'    return;'
'end'
'vhat = vM/speed;'
'lambdaPerp = lambda - (vhat''*lambda)*vhat;'
'den = lambdaPerp''*lambdaPerp;'
'if den < 1.0e-8'
'    aCoop = [0.0; 0.0; 0.0];'
'    return;'
'end'
'rhs = -speed*(uHat + vhat''*lambdaDot);'
'aCoop = rhs*lambdaPerp/den;'
'aCoop = removeAxialComponent(aCoop, vM, minSpeed);'
'end'
'function [ny,nz] = accelToLoad(a, V, theta, psi, lat, H)'
'earth_r = 6371000.0; omega = 7.292116e-5; g0 = 9.806; R = earth_r + H;'
'g = (earth_r/R)^2*g0;'
'eTheta = [-sin(theta)*cos(psi); -sin(theta)*sin(psi); cos(theta)];'
'ePsi = [-sin(psi); cos(psi); 0.0];'
'aTheta = a''*eTheta;'
'aPsi = a''*ePsi;'
'geomTheta = V*cos(theta)/R + 2.0*omega*cos(lat)*sin(psi) + omega^2*R*cos(lat)*(cos(theta)*cos(lat)+sin(theta)*cos(psi)*sin(lat))/V;'
'geomPsi = V*cos(theta)*sin(psi)*tan(lat)/R + 2.0*omega*(sin(lat)-cos(lat)*cos(psi)*tan(theta)) + omega^2*R*cos(lat)*sin(lat)*sin(psi)/max(V*cos(theta),1.0);'
'ny = clamp(aTheta/g + cos(theta) - (V/g)*geomTheta, -20.0, 20.0);'
'nz = clamp(aPsi/g - (V*cos(theta)/g)*geomPsi, -20.0, 20.0);'
'end'
'function a = removeAxialComponent(a, v, minSpeed)'
'speed = norm(v);'
'if speed < minSpeed'
'    return;'
'end'
'vhat = v/speed;'
'a = a - (a''*vhat)*vhat;'
'end'
'function y = limitVectorMagnitude(x, maxMagnitude)'
'xNorm = norm(x);'
'if xNorm > maxMagnitude && xNorm > 0.0'
'    y = x*(maxMagnitude/xNorm);'
'else'
'    y = x;'
'end'
'end'
'function y = gaussianMembership(x, centers, sigma)'
'y = exp(-((x - centers).^2)/(2.0*sigma*sigma));'
'end'
'function y = smoothStep(x)'
'x = clamp(x, 0.0, 1.0);'
'y = x*x*(3.0 - 2.0*x);'
'end'
'function angle = wrapToPiLocal(angle)'
'angle = mod(angle + pi, 2.0*pi) - pi;'
'end'
'function y = clamp(x, lo, hi)'
'y = min(max(x, lo), hi);'
'end'
};
txt = strjoin(lines, newline);
end
